"""empty message

Revision ID: 438ede29d913
Revises: 2bdf0eebc1b2
Create Date: 2021-04-21 22:17:17.860253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438ede29d913'
down_revision = '2bdf0eebc1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csats', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csats', 'rating',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
